import { requireAuth } from '../core/guards.js';
import { mountShell } from '../components/shell.js';
import { modelService } from '../services/model.service.js';
import { statusCard } from '../components/support.js';

if (requireAuth('../login.html')) {
  mountShell('Model Status');
  const app=document.querySelector('#app');
  app.innerHTML='<section class="research-main"><header class="research-hero"><span class="eyebrow">Runtime registry</span><h1>Final research model status</h1><p>Operational availability for frozen research artifacts. Clinical use is disabled.</p><button id="refresh" class="v2-button" type="button">Refresh status</button><small id="checked"></small></header><div id="registry" class="status-grid"><section class="v2-card">Loading runtime status...</section></div><section id="health" class="v2-card">Loading readiness...</section></section>';
  const registry=document.querySelector('#registry'),health=document.querySelector('#health'),checked=document.querySelector('#checked');
  async function load(){registry.innerHTML='<section class="v2-card">Loading runtime status...</section>';health.textContent='Loading readiness...';try{const [status,ready]=await Promise.all([modelService.finalStatus(),modelService.readiness()]);registry.innerHTML=statusCard('Final ML',status.ml,{model:'Logistic Regression',dataset:'WDBC',probability:'Raw',threshold:'0.36'})+statusCard('Final DL',status.dl,{model:'EfficientNet-B0',dataset:'CBIS-DDSM',probability:'Raw decision; Platt display/reliability only',threshold:'0.515'})+`<article class="v2-card status-card"><header><div><span class="eyebrow">Multimodal</span><h2>Experimental fusion</h2></div><span class="status-label experimental">Experimental</span></header><dl><div><dt>Weights</dt><dd>ML 40% · DL 60%</dd></div><div><dt>Validation</dt><dd>Not a validated paired multimodal model</dd></div><div><dt>API status</dt><dd>${status.multimodal_status==='experimental_only'?'experimental_only':'Unavailable'}</dd></div><div><dt>Clinical use</dt><dd>${status.clinical_use===false?'false':'Unavailable'}</dd></div></dl></article>`;health.innerHTML=`<h2>System readiness</h2><div class="health-grid"><span><strong>Service</strong>${ready.status}</span><span><strong>Database</strong>${ready.database}</span><span><strong>Final ML</strong>${ready.final_ml}</span><span><strong>Final DL</strong>${ready.final_dl}</span></div>`;checked.textContent=`Last checked ${new Date().toLocaleString()}`;}catch(error){registry.innerHTML='<section class="v2-card"><h2>Status unavailable</h2><p>Final research runtime unavailable. No fallback is used.</p><button id="retry" class="v2-button" type="button">Retry</button></section>';health.textContent=error.message;document.querySelector('#retry')?.addEventListener('click',load);}}
  document.querySelector('#refresh').addEventListener('click',load); load();
}
