/**
 * frontend/js/pages/privacy.js
 * Privacy Policy & Patient Data Minimization Notice
 */

import { mountShell } from '../components/shell.js';

mountShell('privacy.html');

const app = document.querySelector('#app');

app.innerHTML = `
  <section class="research-main" style="max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem 4rem;">
    <header class="research-hero" style="margin-bottom: 2.5rem;">
      <span class="eyebrow" style="color: var(--teal-600); font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; font-size: 0.8125rem;">Data Governance &amp; Ethics</span>
      <h1 style="font-size: 2.25rem; font-weight: 800; color: var(--slate-900); margin: 0.5rem 0 1rem; line-height: 1.2;">Privacy &amp; Patient Data Minimization Notice</h1>
      <p style="font-size: 1.125rem; color: var(--slate-600); max-width: 720px; line-height: 1.6;">
        Factual disclosure on data collection, local SQLite storage, operator confidentiality, and investigational software limitations.
      </p>
    </header>

    <div class="studio-card" style="border-left: 4px solid var(--amber-500); background: #fffbeb; padding: 1.5rem; border-radius: 8px; margin-bottom: 2rem;">
      <h3 style="color: #92400e; margin: 0 0 0.5rem; font-size: 1.125rem; font-weight: 700;">Investigational Medical Software Disclaimer</h3>
      <p style="color: #b45309; margin: 0; font-size: 0.9375rem; line-height: 1.5;">
        Breast Cancer AI is an investigational academic research prototype designed solely for clinical research and decision-support study. It is <strong>NOT</strong> an FDA/CE-cleared diagnostic device. Predictions generated by this system must never replace formal medical judgment, radiological interpretation, or biopsy-verified histological diagnosis. In an emergency, contact qualified emergency medical services immediately.
      </p>
    </div>

    <div style="display: grid; gap: 1.75rem;">
      <article class="studio-card" style="background: white; border: 1px solid var(--slate-200); padding: 1.75rem; border-radius: 12px;">
        <h2 style="font-size: 1.25rem; font-weight: 700; color: var(--slate-900); margin-top: 0; margin-bottom: 0.75rem;">1. Data Minimization &amp; Information Collected</h2>
        <p style="color: var(--slate-600); font-size: 0.9375rem; line-height: 1.6;">
          This platform is designed according to privacy-by-design and data minimization principles:
        </p>
        <ul style="color: var(--slate-700); font-size: 0.9375rem; line-height: 1.6; padding-left: 1.25rem;">
          <li><strong>Authentication Data:</strong> User email address, cryptographically hashed passwords (OWASP-recommended PBKDF2-HMAC-SHA256 with 600,000 rounds), and random session tokens. Plaintext passwords are never logged or stored.</li>
          <li><strong>Doctor Workspace Records:</strong> Authorized medical operators may optionally attach clinical analyses to patient profiles (Name, Date of Birth, Gender, Clinical Notes) to facilitate longitudinal tracking.</li>
          <li><strong>Diagnostic Diagnostic Inputs:</strong> Fine Needle Aspirate (FNA) numerical morphometric measurements and mammography images uploaded for automated evaluation.</li>
        </ul>
      </article>

      <article class="studio-card" style="background: white; border: 1px solid var(--slate-200); padding: 1.75rem; border-radius: 12px;">
        <h2 style="font-size: 1.25rem; font-weight: 700; color: var(--slate-900); margin-top: 0; margin-bottom: 0.75rem;">2. Data Storage &amp; Operator Isolation</h2>
        <p style="color: var(--slate-600); font-size: 0.9375rem; line-height: 1.6;">
          All operational application data, session records, and patient histories reside exclusively within the deploying organization's self-hosted SQLite database (<code>backend/data/app.db</code>) and local media volumes.
        </p>
        <ul style="color: var(--slate-700); font-size: 0.9375rem; line-height: 1.6; padding-left: 1.25rem;">
          <li><strong>Zero Tracking Cookies:</strong> The system does not utilize commercial advertising trackers, analytics SDKs, or third-party behavioral profiling.</li>
          <li><strong>Zero Data Sale:</strong> No medical records, telemetry, or user account information is sold, rented, or shared with commercial entities.</li>
          <li><strong>AI Advisor Processing:</strong> When the AI Advisor is operating in <code>local</code> mode, reasoning is executed entirely on the server with zero network egress. When configured with cloud providers (Google Gemini or OpenAI), queries are sent using strict API contracts under applicable enterprise terms.</li>
        </ul>
      </article>

      <article class="studio-card" style="background: white; border: 1px solid var(--slate-200); padding: 1.75rem; border-radius: 12px;">
        <h2 style="font-size: 1.25rem; font-weight: 700; color: var(--slate-900); margin-top: 0; margin-bottom: 0.75rem;">3. User Rights &amp; Data Erasure</h2>
        <p style="color: var(--slate-600); font-size: 0.9375rem; line-height: 1.6;">
          Users and clinicians maintain full sovereignty over their entered clinical records:
        </p>
        <ul style="color: var(--slate-700); font-size: 0.9375rem; line-height: 1.6; padding-left: 1.25rem;">
          <li><strong>Patient Record Deletion:</strong> Clinicians can permanently delete patient profiles at any time via Doctor Workspace. Associated predictions and logs are deleted or unlinked via cascading integrity.</li>
          <li><strong>Session Termination:</strong> Users can terminate all active authenticated sessions across devices in Account &amp; Security.</li>
          <li><strong>OAuth Disconnection:</strong> Linked Google accounts can be unlinked at will once a primary account password is established.</li>
        </ul>
      </article>

      <article class="studio-card" style="background: white; border: 1px solid var(--slate-200); padding: 1.75rem; border-radius: 12px;">
        <h2 style="font-size: 1.25rem; font-weight: 700; color: var(--slate-900); margin-top: 0; margin-bottom: 0.75rem;">4. Open Research Attribution</h2>
        <p style="color: var(--slate-600); font-size: 0.9375rem; line-height: 1.6;">
          Demonstration mammograms provided in this research prototype are sourced from The Cancer Imaging Archive (TCIA) CBIS-DDSM collection and are used under Creative Commons Attribution 3.0 Unported (CC BY 3.0). For complete provenance details, see the <a href="research.html" style="color: var(--teal-600); font-weight: 600; text-decoration: underline;">Research Transparency page</a>.
        </p>
      </article>
    </div>
  </section>
`;
